[package]
name = "bread-os-lib"
version = "0.0.1"
authors = ["himself65 <himself65@outlook.com>"]
edition = "2018"

[dependencies]
rlibc = "1.0"

[build-dependencies]
dotenv = "0.15.0"
bindgen = "0.55"
