name: CI runner

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install Requirement
        run: sudo apt install cmake make gcc g++ build-essential uuid-dev iasl python
      - name: Build Kernel with Makefile
        run: make
      - name: Build Kernel with Cmake
        run: cmake .